name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Can add
      id: can-add
      uses: education/autograding-io-grader@v1
      with:
        test-name: Can add
        setup-command: ''
        command: python ./testing_code.py
        input: ''
        expected-output: ''
        comparison-method: contains
        timeout: 10
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        CAN-ADD_RESULTS: "${{steps.can-add.outputs.result}}"
      with:
        runners: can-add
